=== sifatsultan/yushi/markup_language/hw1/yushi_3/StudentDetails.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT students (student)>

<!ELEMENT student (image,title,studentid,surname,preferred_name,given_name,gender,dateofbirth,email,notes,contact,course_attempts, home_address,co_address)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT studentid (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT preferred_name (#PCDATA)>
<!ELEMENT given_name (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT dateofbirth (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT notes (note)>
<!ELEMENT note (#PCDATA)>

<!ELEMENT contact (home,work,mobile,fax,home2,work2,mobile2,fax2)>
<!ELEMENT home (#PCDATA)>
<!ELEMENT work (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT home2 (#PCDATA)>
<!ELEMENT work2 (#PCDATA)>
<!ELEMENT mobile2 (#PCDATA)>
<!ELEMENT fax2 (#PCDATA)>

<!ELEMENT course_attempts (course)>
<!ELEMENT course (status,unit_code,courseURL)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT unit_code (#PCDATA)>
<!ELEMENT courseURL (#PCDATA)>


<!ELEMENT home_address (start_date,street1,suburb1,postcode1)>
<!ELEMENT start_date (#PCDATA)>
<!ELEMENT street1 (#PCDATA)>
<!ELEMENT suburb1 (#PCDATA)>
<!ELEMENT postcode1 (#PCDATA)>


<!ELEMENT home_address (start_date,street2,suburb2,postcode2)>
<!ELEMENT start_date (#PCDATA)>
<!ELEMENT street1 (#PCDATA)>
<!ELEMENT suburb1 (#PCDATA)>
<!ELEMENT postcode1 (#PCDATA)>

=== sifatsultan/yushi/markup_language/hw1/yushi_3/students.xml
<?xml version="1.0" encoding="UTF-8"?> 

<?xml-stylesheet type="text/xsl" href="test1.xslt"?>

<!DOCTYPE students SYSTEM "StudentDetails.dtd">

<students>
	<student>
		<image>students/student1.jpg</image>
		<title>Miss</title>
		<studentid>5252</studentid>
		<surname>Smith</surname>
		<preferred_name>Jen</preferred_name>
		<given_name>Jen</given_name>
		<gender>M</gender>
		<dateofbirth>6/8/1990</dateofbirth>
		<email>james@ecu.com.au</email>

		<notes>
			<note>sdfdhfgd</note>
		</notes>
		


		<contact>

			<home>98789858</home>
			<work>0458974895</work>
			<mobile>0458974895</mobile>
			<fax>(545)2556</fax>

			<home2>98789858</home2>
			<work2>0458974895</work2>
			<mobile2>0458974895</mobile2>
			<fax2>(545)2556</fax2>

		</contact>


		<course_attempts>
			<course>
				<status>ENROLLED</status>
				<unit_code>U67</unit_code>
				<courseURL>http://www.ecu.edu.au/handbook/course?id=U67&amp;year=2017
				</courseURL>
			</course>

			<course>
				<status>COMPLETED</status>
				<unit_code>G95</unit_code>
				<courseURL>http://www.ecu.edu.au/handbook/course?id=G95&amp;year=2017
				</courseURL>
			</course>

		</course_attempts>

		<home_address>
			<start_date>29/9/2007</start_date>
			<street1>5 Burns Beach Rd</street1>
			<suburb1>Burns Beach</suburb1>
			<postcode1>6029</postcode1>

		</home_address>


		<co_address>
			<start_date>29/9/2007</start_date>
			<street2>5 Burns Beach Rd</street2>
			<suburb2>Burns Beach</suburb2>
			<postcode2>6029</postcode2>
		</co_address>

	</student>

	<student>
		<image>students/student2.jpg</image>
		<title>Mr</title>
		<studentid>5252</studentid>
		<surname>Armstrong</surname>
		<preferred_name>John</preferred_name>
		<given_name>John</given_name>
		<gender>M</gender>
		<dateofbirth>6/8/1993</dateofbirth>
		<email>John@ecu.com.au</email>

		<notes>
			<note>sdfdhfgd</note>
		</notes>

		<contact>

			<home>98789858</home>
			<work>0458974895</work>
			<mobile>0458974895</mobile>
			<fax>(545)2556</fax>

			<home2>98789858</home2>
			<work2>0458974895</work2>
			<mobile2>0458974895</mobile2>
			<fax2>(545)2556</fax2>

		</contact>


		<course_attempts>

			<course>
				<status>ENROLLED</status>
				<unit_code>U67</unit_code>
				<courseURL>http://www.ecu.edu.au/handbook/course?id=U67&amp;year=2017
				</courseURL>
			</course>

			<course>
				<status>DISCONT</status>
				<unit_code>Y78</unit_code>
				<courseURL>http://www.ecu.edu.au/handbook/course?id=U67&amp;year=2017
				</courseURL>
			</course>
		</course_attempts>

		<home_address>
			<start_date>29/9/2007</start_date>
			<street1>5 Burns Beach Rd</street1>
			<suburb1>Burns Beach</suburb1>
			<postcode1>6029</postcode1>

		</home_address>


		<co_address>
			<start_date>29/9/2007</start_date>
			<street2>5 Burns Beach Rd</street2>
			<suburb2>Burns Beach</suburb2>
			<postcode2>6029</postcode2>
		</co_address>

	</student>

	<student>
		<image>students/student3.jpg</image>
		<studentid>5252</studentid>
		<title>Mr</title>
		<surname>Stevens</surname>
		<preferred_name>John</preferred_name>
		<given_name>John</given_name>
		<gender>M</gender>
		<dateofbirth>6/8/1993</dateofbirth>
		<email>John@ecu.com.au</email>


		<notes>
			<note>sdfdhfgd</note>
		</notes>
		<contact>

			<home>98789858</home>
			<work>0458974895</work>
			<mobile>0458974895</mobile>
			<fax>(545)2556</fax>

			<home2>98789858</home2>
			<work2>0458974895</work2>
			<mobile2>0458974895</mobile2>
			<fax2>(545)2556</fax2>


		</contact>


		<course_attempts>
			<course>
				<status>ENROLLED</status>
				<unit_code>U67</unit_code>
				<courseURL>http://www.ecu.edu.au/handbook/course?id=U67&amp;year=2017
				</courseURL>
			</course>

			<course>
				<status>COMPLETED</status>
				<unit_code>G95</unit_code>
				<courseURL>http://www.ecu.edu.au/handbook/course?id=G95&amp;year=2017
				</courseURL>
			</course>


		</course_attempts>

		<home_address>
			<start_date>27/2/2017</start_date>
			<street1>5 Burns Beach Rd</street1>
			<suburb1>Burns Beach</suburb1>
			<postcode1>6029</postcode1>

		</home_address>


		<co_address>
			<start_date>27/2/2017</start_date>
			<street2>5 Burns Beach Rd</street2>
			<suburb2>Burns Beach</suburb2>
			<postcode2>6029</postcode2>
		</co_address>
	</student>

	<student>
		<image>students/student3.jpg</image>
		<studentid>5252</studentid>
		<title>Mr</title>
		<surname>Stevens</surname>
		<preferred_name>John</preferred_name>
		<given_name>John</given_name>
		<gender>M</gender>
		<dateofbirth>6/8/1993</dateofbirth>
		<email>John@ecu.com.au</email>
		<contact>

			<home>98789858</home>
			<work>0458974895</work>
			<mobile>0458974895</mobile>
			<fax>(545)2556</fax>

			<home2>98789858</home2>
			<work2>0458974895</work2>
			<mobile2>0458974895</mobile2>
			<fax2>(545)2556</fax2>


		</contact>

		<course_attempts>
			<course>
				<status>ENROLLED</status>
				<unit_code>U67</unit_code>
				<courseURL>http://www.ecu.edu.au/handbook/course?id=U67&amp;year=2017
				</courseURL>
			</course>

			<course>
				<status>COMPLETED</status>
				<unit_code>G95</unit_code>
				<courseURL>http://www.ecu.edu.au/handbook/course?id=G95&amp;year=2017
				</courseURL>
			</course>

		</course_attempts>

		<home_address>
			<start_date>27/2/2017</start_date>
			<street1>5 Burns Beach Rd</street1>
			<suburb1>Burns Beach</suburb1>
			<postcode1>6029</postcode1>

		</home_address>


		<co_address>
			<start_date>27/2/2017</start_date>
			<street2>5 Burns Beach Rd</street2>
			<suburb2>Burns Beach</suburb2>
			<postcode2>6029</postcode2>
		</co_address>

	</student>


</students>
